spring:
  application:
    name: converter

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
#      host: redis
      host: localhost
      port: 6379


