spring:
  application:
    name: converter

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring
    username: postgres
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/spring
    user: postgres
    password: ${DB_PASSWORD}

  data:
    redis:
      host: redis
#      host: localhost
      port: 6379


